// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhamasySystem2.Model;

namespace PhamasySystem2.Migrations.Customer
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20210516164639_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhamasySystem2.Model.Customers", b =>
                {
                    b.Property<Guid>("CId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("AllergyMedicines");

                    b.Property<string>("CName");

                    b.Property<string>("NIC");

                    b.Property<string>("PNum");

                    b.HasKey("CId");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
